# Setup
paginate: 1
baseurl: ""
permalink: /:categories/:title
lang: en_US
timezone: America/New_York
# jekyll doesn't understand that 11:30 is before 11:40 for some reason
future: true

# SEO
url: https://tisawesomeness.github.io
title: Tis
description: "You can call me Tis. Developer, sysadmin, technical Minecrafter."
author:
  name: Tis_awesomeness
  url: https://github.com/Tisawesomeness
  github: Tisawesomeness
social:
  links:
    - https://bsky.app/profile/tis.codes

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Snapshots
    url: /snapshots

#  - title: Posts
#    url: /archive

  - title: About
    url: /about

# RSS
feed_items: 10
feed_update_period: hourly
feed_update_frequency: 1

